version: '3.8'

services:
  fileservice.presentation:
    image: fileservice.presentation
    build:
      context: ./src/Services/FIleService/
      dockerfile: FIleService.Presentation/Dockerfile
    ports:
      - "8083:8083"
    networks:
      - test-task-network
    environment:
      - ASPNETCORE_URLS=http://+:8083
      - ConnectionStrings__ConnectionString=Host=fileservice_db;Port=5432;Database=fileservice;Username=postgres;Password=postgres
    depends_on:
      - fileservice_db

  fileservice_db:
    image: postgres:latest
    container_name: fileservice_db
    environment:
      POSTGRES_DB: fileservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - file-postgres-data:/var/lib/postgresql/data
    networks:
      - test-task-network

  statementprocessingservice.presentation:
    image: statementprocessingservice.presentation
    build:
      context: ./src/Services/StatementProcessingService/
      dockerfile: StatementProcessingService.Presentation/Dockerfile
    depends_on:
      - statementprocessingservice_db
    environment:
      - ASPNETCORE_URLS=http://+:8082
      - ConnectionStrings__ConnectionString=Host=statementprocessingservice_db;Port=5432;Database=statement_processing_service;Username=postgres;Password=postgres
    ports:
      - "8082:8082"
    networks:
      - test-task-network

  statementprocessingservice_db:
    image: postgres:latest
    container_name: statementprocessingservice_db
    environment:
      POSTGRES_DB: statement_processing_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - statement-processing-postgres-data:/var/lib/postgresql/data
    networks:
      - test-task-network

volumes:
  statement-processing-postgres-data:
  file-postgres-data:

networks:
  test-task-network:
    driver: bridge