services:
  fileservice.presentation:
    image: fileservice.presentation
    build:
      context: ./src/Services/FIleService/
      dockerfile: FIleService.Presentation/Dockerfile
      
  fileservice_db:
    image: postgres:latest
    container_name: fileservice_db
    environment:
      POSTGRES_DB: fileservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql